version: '3.8'

networks:
  docker-net:
    driver: bridge

services:
  backend:
    build: ./
    container_name: backend-slocked
    ports:
      - 5000:5000
    links:
      - database
    networks:
      - docker-net
    depends_on:
      - database
    command: npm run start

  database:
    image: mysql:8.0
    container_name: database-slocked
    restart: always
    networks:
      - docker-net
    environment:
      - MYSQL_ROOT_PASSWORD=0038
      - MYSQL_DATABASE=rfid
    ports:
      - 3306:3306